src/ralph/accounts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import re_path

from ralph.accounts.views import (
    CurrentUserInfoView,
    InventoryTagConfirmationView,
    InventoryTagView,
    UserProfileView,
)

urlpatterns = [
    re_path(
        r"^user_profile/?$",
        login_required(UserProfileView.as_view()),
        name="user_profile",
    ),
    re_path(
        r"^my_equipment/?$",
        login_required(CurrentUserInfoView.as_view()),
        name="current_user_info",
    ),
    re_path(
        r"^my_equipment/inventory_tag/" r"(?P<asset_id>[0-9]+)/(?P<answer>yes|no)/$",
        login_required(InventoryTagConfirmationView.as_view()),
        name="inventory_tag_confirmation",
    ),
    re_path(
        r"^my_equipment/inventory_tag/$",
        login_required(InventoryTagView.as_view()),
        name="inventory_tag",
    ),
]

src/ralph/accounts/models.py
# -*- coding: utf-8 -*-
import hashlib

from ralph.lib.dj_choices import Country
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.encoding import force_bytes
from django.utils.translation import gettext_lazy as _
from rest_framework.authtoken.models import Token

from ralph.admin.autocomplete import AutocompleteTooltipMixin
from ralph.lib.mixins.models import AdminAbsoluteUrlMixin, NamedMixin
from ralph.lib.permissions.models import (
    PermByFieldMixin,
    PermissionsForObjectMixin,
    user_permission,
)
from ralph.lib.visibility_scope.models import ServiceBasedVisibilityScope


@user_permission
def has_region(user):
    """
    Check if user has rights to region.
    """
    return models.Q(id__in=user.regions_ids)


class Region(AdminAbsoluteUrlMixin, PermissionsForObjectMixin, NamedMixin):
    country = models.PositiveIntegerField(
        verbose_name=_("country"),
        choices=Country(),
        default=Country.pl.id,
    )
    stocktaking_enabled = models.BooleanField(default=False)

    """Used for distinguishing the origin of the object by region"""

    class Permissions:
        has_access = has_region


@user_permission
def object_has_region(user):
    """
    Check if object's region is one of user regions.
    """
    return models.Q(region__in=user.regions_ids)


class Regionalizable(PermissionsForObjectMixin):
    region = models.ForeignKey(
        Region, blank=False, null=False, on_delete=models.CASCADE
    )

    class Meta:
        abstract = True

    class Permissions:
        has_access = object_has_region


class Team(AdminAbsoluteUrlMixin, NamedMixin):
    pass


class RalphUser(
    PermByFieldMixin, AbstractUser, AdminAbsoluteUrlMixin, AutocompleteTooltipMixin
):
    country = models.PositiveIntegerField(
        verbose_name=_("country"),
        choices=Country(),
        default=Country.pl.id,
    )
    city = models.CharField(
        verbose_name=_("city"),
        max_length=30,
        blank=True,
    )
    company = models.CharField(
        verbose_name=_("company"),
        max_length=64,
        blank=True,
    )
    employee_id = models.CharField(
        verbose_name=_("employee id"),
        max_length=64,
        blank=True,
    )
    profit_center = models.CharField(
        verbose_name=_("profit center"),
        max_length=1024,
        blank=True,
    )
    cost_center = models.CharField(
        verbose_name=_("cost center"),
        max_length=1024,
        blank=True,
    )
    department = models.CharField(
        verbose_name=_("department"),
        max_length=128,
        blank=True,
    )
    manager = models.CharField(
        verbose_name=_("manager"),
        max_length=1024,
        blank=True,
    )
    location = models.CharField(
        verbose_name=_("location"),
        max_length=128,
        blank=True,
    )
    segment = models.CharField(
        verbose_name=_("segment"),
        max_length=256,
        blank=True,
    )
    regions = models.ManyToManyField(Region, related_name="users", blank=True)
    service_visibility_scopes = models.ManyToManyField(
        ServiceBasedVisibilityScope, related_name="users", blank=True
    )
    team = models.ForeignKey(
        Team,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )

    autocomplete_tooltip_fields = [
        "employee_id",
        "company",
        "department",
        "manager",
        "profit_center",
        "cost_center",
    ]
    autocomplete_words_split = True

    class Meta(AbstractUser.Meta):
        swappable = "AUTH_USER_MODEL"

    def __str__(self):
        full_name = self.get_full_name()
        if full_name:
            return "{} ({})".format(full_name, self.username)
        return super().__str__()

    @property
    def api_token_key(self):
        try:
            return self.auth_token.key
        except Token.DoesNotExist:
            return None

    @property
    def regions_ids(self):
        """
        Get region ids without additional SQL joins.
        """
        return self.regions.through.objects.filter(ralphuser=self).values_list(
            "region_id", flat=True
        )

    def has_any_perms(self, perms, obj=None):
        return any([self.has_perm(p, obj=obj) for p in perms])

    def save(self, *args, **kwargs):
        if isinstance(self.country, str):
            self.country = Country.from_name(self.country.lower()).id
        elif self.country is None:
            self.country = Country.pl.id
        return super().save(*args, **kwargs)

    @property
    def autocomplete_str(self):
        return "{} <i>{}</i>".format(str(self), self.department)

    @property
    def permissions_hash(self):
        """
        Property used in template as a param to cache invalidation.
        Hash for caching is calculated from user ID and its permissions.
        """
        perms_set = frozenset(self.get_all_permissions())
        key = ":".join((str(self.id), str(hash(perms_set))))
        return hashlib.md5(force_bytes(key)).hexdigest()


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    """
    Create token for newly created user.
    """
    if created:
        Token.objects.create(user=instance)

src/ralph/accounts/templates/ralphuser/inventory_tag_confirmation.html
{% extends "admin/base_site.html" %}
{% load i18n static table %}

{% block title %}
  {% trans "Asset possession confirmation" %}
{% endblock %}

{% block content %}
<div id="content-main" class="row">
  <div class="large-6 columns">
    {% if answer == "yes" %}
      <h1>{% trans "Are you sure you have following item?" %}</h1>
    {% elif answer ==  "no" %}
      <h1>{% trans "Are you sure you don't have this item?" %}</h1>
    {% endif %}
    {% table asset_details.get_table_content %}
    <form action={% url 'inventory_tag' %} method="POST">
      {% csrf_token %}
      <input type="hidden" name="asset_id" value="{{ asset_id }}" />
      <input type="hidden" name="answer" value="{{ answer }}" />
      <a href={% url 'current_user_info' %} class= "button small alert left">
          Cancel</a>
      <input type="submit" name="confirm_button" value="Yes"
          class="button small success left" autocomplete="off" />
    </form>
  </div>
  <div class="large-6 columns"></div>
</div>
{% endblock %}

src/ralph/accounts/templates/ralphuser/my_equipment.html
{% extends "admin/base_site.html" %}

{% load i18n table %}

{% block content %}
  <div class="large-12 columns">
    <h1>{{ request.user.first_name }} {{ request.user.last_name }}</h1>

    {% include 'ralphuser/partials/accept_assets.html' with title="Assets to accept" action="accept" transition_id=acceptance_transition_id transition_exists=acceptance_transition_exists assets=assets_to_accept %}
    {% include 'ralphuser/partials/accept_assets.html' with title="Assets to loan" action="loan" transition_id=loan_transition_id transition_exists=loan_transition_exists assets=assets_to_loan %}

    {% if managing_devices_moved_info %}
      {{ managing_devices_moved_info|safe }}
    {% endif %}

    <h5>{% trans 'Assigned assets' %}:</h5>
    {% table asset_list.get_table_content %}

    <h5>{% trans 'Assigned licences' %}:</h5>
    {% table licence_list.get_table_content %}

  </div>
{% endblock %}

src/ralph/accounts/templates/ralphuser/user_additional_info.html
{% extends BASE_TEMPLATE %}
{% load i18n table %}
{% block view_content %}
<div class="large-12 columns">
  <h1>{{ object.first_name }} {{ object.last_name }}</h1>

  <h5>{% trans 'Assigned assets' %}:</h5>
  {% table asset_list.get_table_content %}

  <h5>{% trans 'Assigned licences' %}:</h5>
  {% table licence_list.get_table_content %}
</div>
{% endblock %}

src/ralph/accounts/templates/ralphuser/user_profile.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block title %}
  {% trans "My profile" %}
{% endblock %}

{% block content %}
<h1>{% trans "My profile" %}</h1>

<div id="content-main" class="row">
  <div class="large-6 columns">
    <fieldset>
      <legend>{% trans "Personal info" %}</legend>
      <div class="row">
        <div class="small-6 columns">
          <dl>
            <dt>{% trans "Username" %}</dt>
            <dd>{{ request.user.username }}</dd>
            <dt>{% trans "Full name" %}</dt>
            <dd>{{ request.user.get_full_name }}</dd>
          </dl>
        </div>
        <div class="small-6 columns end">
          <dl>
            <dt>{% trans "API Token" %}</dt>
            <dd>{{ request.user.api_token_key }}</dd>
          </dl>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>{% trans "Profile" %}</legend>
      <div class="row">
        <div class="small-6 columns">
          <dl>
            <dt>{% trans "Country" %}</dt>
            <dd>{{ request.user.get_country_display }}</dd>
            <dt>{% trans "City" %}</dt>
            <dd>{{ request.user.get_city_display }}</dd>
          </dl>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>{% trans "Job info" %}</legend>
      <div class="row">
        <div class="small-6 columns">
          <dl>
            <dt>{% trans "Company" %}</dt>
            <dd>{{ request.user.company }}</dd>
            <dt>{% trans "Profit center" %}</dt>
            <dd>{{ request.user.profit_center }}</dd>
            <dt>{% trans "Cost center" %}</dt>
            <dd>{{ request.user.cost_center }}</dd>
            <dt>{% trans "Department" %}</dt>
            <dd>{{ request.user.department }}</dd>
          </dl>
        </div>
        <div class="small-6 columns end">
          <dl>
            <dt>{% trans "Manager" %}</dt>
            <dd>{{ request.user.manager }}</dd>
            <dt>{% trans "Location" %}</dt>
            <dd>{{ request.user.location }}</dd>
            <dt>{% trans "Segment" %}</dt>
            <dd>{{ request.user.segment }}</dd>
          </dl>
        </div>
      </div>
    </fieldset>
  </div>
  <div class="large-6 columns">
    <fieldset>
      <legend>{% trans "Preferences" %}</legend>
      {% get_current_language as LANGUAGE_CODE %}
      {% get_available_languages as LANGUAGES %}
      <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
        <input name="next" type="hidden" value="." />
          {% csrf_token %}
          <select name="language">
            {% for lang in LANGUAGES %}
              <option value="{{ lang.0 }}"{% if lang.0 == LANGUAGE_CODE %} selected{% endif %}>{{ lang.1 }}</option>
            {% endfor %}
          </select>
        <button>{% trans "Change language" %}</button>
      </form>
    </fieldset>
  </div>
</div>
{% endblock %}

src/ralph/accounts/templates/ralphuser/user_transition_history.html
{% extends BASE_TEMPLATE %}
{% load i18n table %}
{% block view_content %}
<div class="large-12 columns">
  <h1>{% trans 'User transition history' %}</h1>
  <br /> <br />
  {% include 'admin/templatetags/transition_history.html' %}
</div>
{% endblock %}